// Generated by CoffeeScript 1.6.3
(function() {
  var AmorphousRecipe, CraftingThesaurus, Inventory, ItemPile, PositionalRecipe, Recipe, craftingGrid, test, _ref;

  test = require('tape');

  _ref = require('./'), Recipe = _ref.Recipe, AmorphousRecipe = _ref.AmorphousRecipe, PositionalRecipe = _ref.PositionalRecipe, CraftingThesaurus = _ref.CraftingThesaurus;

  Inventory = require('inventory');

  ItemPile = require('itempile');

  test('thesaurus register', function(t) {
    t.equals(CraftingThesaurus.matchesName('logOak', new ItemPile('plankOak')), false);
    CraftingThesaurus.registerName('blackDye', new ItemPile('squidInk'));
    CraftingThesaurus.registerName('blackDye', new ItemPile('syntheticBlackInk'));
    CraftingThesaurus.registerName('whiteDye', new ItemPile('bonemeal'));
    CraftingThesaurus.registerName('whiteDye', new ItemPile('bleach'));
    t.equals(CraftingThesaurus.matchesName('blackDye', new ItemPile('squidInk')), true);
    t.equals(CraftingThesaurus.matchesName('blackDye', new ItemPile('syntheticBlackInk')), true);
    t.equals(CraftingThesaurus.matchesName('blackDye', new ItemPile('something')), false);
    t.equals(CraftingThesaurus.matchesName('whiteDye', new ItemPile('bonemeal')), true);
    t.equals(CraftingThesaurus.matchesName('whiteDye', new ItemPile('bleach')), true);
    t.equals(CraftingThesaurus.matchesName('whiteDye', new ItemPile('dirt')), false);
    return t.end();
  });

  craftingGrid = function(names) {
    var i, input, _i, _ref1;
    input = new Inventory(4);
    for (i = _i = 0, _ref1 = names.length; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
      input.set(i, new ItemPile(names[i], 1));
    }
    return input;
  };

  test('simple recipe match', function(t) {
    var r;
    r = new AmorphousRecipe(['log'], new ItemPile('plank'));
    t.equals(r.matches(craftingGrid(['log'])), true);
    t.equals(r.matches(craftingGrid([void 0, 'log'])), true);
    t.equals(r.matches(craftingGrid([void 0, void 0, 'log'])), true);
    t.equals(r.matches(craftingGrid([void 0, void 0, void 0, 'log'])), true);
    return t.end();
  });

  test('double ingredients', function(t) {
    var r;
    r = new AmorphousRecipe(['plank', 'plank'], new ItemPile('stick'));
    t.equals(r.matches(craftingGrid(['plank'])), false);
    t.equals(r.matches(craftingGrid(['plank', 'plank'])), true);
    t.equals(r.matches(craftingGrid(['plank', 'plank', 'plank'])), true);
    t.equals(r.matches(craftingGrid([void 0, 'plank', 'plank'])), true);
    t.equals(r.matches(craftingGrid([void 0, void 0, 'plank', 'plank'])), true);
    return t.end();
  });

  test('craft thesaurus', function(t) {
    var r;
    r = new AmorphousRecipe(['log'], new ItemPile('plank'));
    CraftingThesaurus.registerName('log', new ItemPile('logOak'));
    CraftingThesaurus.registerName('log', new ItemPile('logBirch'));
    t.equals(r.matches(craftingGrid(['log'])), true);
    t.equals(r.matches(craftingGrid(['logOak'])), true);
    t.equals(r.matches(craftingGrid(['logBirch'])), true);
    t.equals(r.matches(craftingGrid(['logWhatever'])), false);
    return t.end();
  });

  test('take craft empty', function(t) {
    var grid, output, r;
    r = new AmorphousRecipe(['log'], new ItemPile('plank'));
    grid = craftingGrid(['log']);
    output = r.craft(grid);
    t.equals(!!output, true);
    console.log('output', output);
    t.equals(output.item, 'plank');
    t.equals(grid.get(0), void 0);
    t.equals(grid.get(1), void 0);
    t.equals(grid.get(2), void 0);
    t.equals(grid.get(3), void 0);
    return t.end();
  });

  test('take craft leftover', function(t) {
    var grid, output, r;
    r = new AmorphousRecipe(['log'], new ItemPile('plank'));
    grid = new Inventory(4);
    grid.set(0, new ItemPile('log', 10));
    output = r.craft(grid);
    t.equals(!!output, true);
    console.log('output', output);
    t.equals(output.item, 'plank');
    console.log('new grid', grid);
    t.equals(grid.get(0) !== void 0, true);
    t.equals(grid.get(0).count, 9);
    t.equals(grid.get(0).item, 'log');
    t.equals(grid.get(1), void 0);
    t.equals(grid.get(2), void 0);
    t.equals(grid.get(3), void 0);
    return t.end();
  });

}).call(this);
