// Generated by CoffeeScript 1.6.3
(function() {
  var AmorphousRecipe, Inventory, ItemPile, PositionalRecipe, Recipe, craftingGrid, test, _ref;

  test = require('tape');

  _ref = require('./'), Recipe = _ref.Recipe, AmorphousRecipe = _ref.AmorphousRecipe, PositionalRecipe = _ref.PositionalRecipe;

  Inventory = require('inventory');

  ItemPile = require('itempile');

  craftingGrid = function(names) {
    var i, input, _i, _ref1;
    input = new Inventory(4);
    for (i = _i = 0, _ref1 = names.length; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
      input.set(i, new ItemPile(names[i], 1));
    }
    return input;
  };

  test('simple recipe match', function(t) {
    var r;
    r = new AmorphousRecipe(['log'], 'plank');
    t.equals(r.matches(craftingGrid(['log'])), true);
    t.equals(r.matches(craftingGrid([void 0, 'log'])), true);
    t.equals(r.matches(craftingGrid([void 0, void 0, 'log'])), true);
    t.equals(r.matches(craftingGrid([void 0, void 0, void 0, 'log'])), true);
    return t.end();
  });

  test('double ingredients', function(t) {
    var input, r;
    r = new AmorphousRecipe(['plank', 'plank'], 'stick');
    console.log(r);
    input = new Inventory(4);
    return t.end();
  });

}).call(this);
